import ROOT
ROOT.gStyle.SetOptStat(0)
ROOT.gStyle.SetPadTopMargin(0.05)
ROOT.gStyle.SetPadRightMargin(0.18)
ROOT.gStyle.SetPadBottomMargin(0.16)
ROOT.gStyle.SetPadLeftMargin(0.18)
ROOT.gStyle.SetPaintTextFormat(".2f")
ROOT.gStyle.SetTextFont(42)
ROOT.gStyle.SetLabelSize(0.05, 'xyz')
ROOT.gStyle.SetTitleSize(0.05, 'xyz')
ROOT.gStyle.SetTitleOffset(1.3, 'x')
ROOT.gStyle.SetTitleOffset(1.7, 'y')
ROOT.gStyle.SetTitleOffset(1.3, 'z')
ROOT.gStyle.SetPadTickX(1)
ROOT.gStyle.SetPadTickY(1)
